#!/usr/bin/env bash
# Start Apache so as to return and fix issues
# page conatining Hello Holberton

sudo apt-get update
sudo apt-get install -y apache2

echo "Hello Holberton" > /var/www/html/index.html
sudo service apache2 start 
