#!/usr/bin/env bash
# Config Nginx so that its HTTP response contains a custom header

# Update 
sudo apt-get update 
sudo apt-get install -y nginx

# nginx page change

echo "Holberton School" | sudo tee /var/www/html/index.html

# Configure redirection for /redirect_me

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

#HTTP header
sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors
sudo nginx -t

# restart nginx
sudo service nginx restart
