#!/usr/bin/env bash
# Install  load balancer
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 6541-web-01 54.175.105.22:80 check
        server 6541-web-02 54.175.110.39:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to get started
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart nginx
sudo service haproxy restart
