#!/usr/bin/env bash
# Configures a new Ubuntu machine 
# INSTALLING Nginx on port 80

echo -e "installing Nginx\n"
sudo apt-get update -y -qq && \
    sudo apt-get install nginx -y

# Starting nginx service
sudo service nginx start

# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index with "Holberton School"
echo -e "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Restarting nginx
sudo service nginx restart

echo -e "Completed\n"
