#!/usr/bin/env bash

# This script installs and configures Nginx on an Ubuntu 16.04 LTS server

# Update package list
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Ensure Nginx is running
sudo service nginx start

# Configure Nginx to return 'Holberton School for the win!'
echo 'Holberton School for the win!' | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx without using systemctl
sudo service nginx restart
