#!/usr/bin/env bash
# Script for 404 page

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Replace the default Nginx page
echo "Holberton School" | sudo tee /var/www/html/index.html

# Configure redirection for /redirect_me
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# 404 error page
echo"Ceci n'est pas une pag" | sudo tee /var/www/html/404.html

replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation =\/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$replace/" /etc/nginx/sites-enabled/default

#restart nginx

sudo service nginx restart
