#!/usr/bin/env bash
# Configures Nginx server with a custom 404 page

# Install nginx if not already installed
sudo apt-get -y update
sudo apt-get -y install nginx

# Start nginx service
sudo systemctl start nginx

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure nginx to use the custom 404 page
config_file="/etc/nginx/sites-available/default"

# Check if the location block already exists
if ! grep -q "location = /404.html" "$config_file"; then
        error_config="error_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
        # Add the error_page directive to the server block
        sudo sed -i "/server_name _;/a\\\\t$error_config" "$config_file"
fi

# Test nginx configuration
sudo nginx -t

# Restart nginx to apply changes
sudo systemctl restart nginx

# Added Debugging
echo "Nginx configuration file:"
sudo cat /etc/nginx/sites-available/default
echo "404.html file content:"
sudo cat /var/www/html/404.html
